import Navbar from "./Navbar";
import Hero from "./Hero";
import Services from "./Services";
import Aboutpage from "./Aboutpage";
import Slider from "./Slider";
import Contact from "./Contact";
import Partners from "./Partners";
import Scroll from "./Scroll";
import Footer from './Footer'
import Quote from "./Quote";
import Team from "./Team";
import Satelite from "./Satelite";
import Login from "./Login";
import Verify from './Verify'
import BuyToken from "./BuyToken";
import UploadCar from "./UploadCar";
import Sellersignup from "./Sellersignup";
import Forgotsellerpassword from "./Forgotsellerpassword";
export { Satelite, Team, Quote,Footer,Scroll, Partners,Contact,Slider,Hero,Navbar,Services,Aboutpage,BuyToken,UploadCar,Login, Verify,Sellersignup,Forgotsellerpassword}